/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estacionamientonivel;

import java.awt.Color;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author vanes
 */
public class login_usr extends javax.swing.JFrame {

    int xMouse, yMouse;
    private int counter = 0;
    
    public login_usr() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panel_admin = new javax.swing.JPanel();
        lb_admin = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        panel_exit = new javax.swing.JPanel();
        lb_exit = new javax.swing.JLabel();
        panel_root = new javax.swing.JPanel();
        lb_root = new javax.swing.JLabel();
        panel_entrar = new javax.swing.JPanel();
        lb_entrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 260, 530));

        panel_admin.setBackground(new java.awt.Color(255, 255, 255));

        lb_admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_admin.setText("Aministrador");
        lb_admin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_adminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel2.add(panel_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 150, 70));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_exit.setBackground(new java.awt.Color(255, 255, 255));

        lb_exit.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lb_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exit.setText("X");
        lb_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_exitLayout = new javax.swing.GroupLayout(panel_exit);
        panel_exit.setLayout(panel_exitLayout);
        panel_exitLayout.setHorizontalGroup(
            panel_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exit, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        panel_exitLayout.setVerticalGroup(
            panel_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        header.add(panel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 70));

        panel_root.setBackground(new java.awt.Color(255, 255, 255));

        lb_root.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_root.setText("Root");
        lb_root.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_root.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_rootMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_rootMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_rootMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_rootLayout = new javax.swing.GroupLayout(panel_root);
        panel_root.setLayout(panel_rootLayout);
        panel_rootLayout.setHorizontalGroup(
            panel_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_root, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        panel_rootLayout.setVerticalGroup(
            panel_rootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_root, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        header.add(panel_root, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 150, 70));

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        lb_entrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lb_entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_entrar.setText("Entrar");
        lb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_entrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_entrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_entrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_entrarLayout = new javax.swing.GroupLayout(panel_entrar);
        panel_entrar.setLayout(panel_entrarLayout);
        panel_entrarLayout.setHorizontalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panel_entrarLayout.setVerticalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(panel_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 120, 60));

        jLabel2.setText("INICIAR SESIÓN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txt_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_usuario.setText("Ingrese su nombre de usuario");
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        jPanel2.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 370, 50));

        txt_pass.setForeground(new java.awt.Color(204, 204, 204));
        txt_pass.setText("*****");
        txt_pass.setBorder(null);
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passMousePressed(evt);
            }
        });
        jPanel2.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 370, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 370, 30));

        message.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel2.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_rootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_rootMouseClicked
        // TODO add your handling code here:
        Login abrir=new Login();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_lb_rootMouseClicked

    private void lb_rootMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_rootMouseEntered
        // TODO add your handling code here:
        panel_root.setBackground(Color.lightGray);
        lb_root.setForeground(Color.black);
    }//GEN-LAST:event_lb_rootMouseEntered

    private void lb_rootMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_rootMouseExited
        // TODO add your handling code here:
        panel_root.setBackground(Color.white);
        lb_root.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_rootMouseExited

    private void lb_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_adminMouseClicked
        // TODO add your handling code here:+
        login_admin abrir=new login_admin();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_lb_adminMouseClicked

    private void lb_adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_adminMouseEntered
        // TODO add your handling code here:
        panel_admin.setBackground(Color.lightGray);
        lb_admin.setForeground(Color.black);
    }//GEN-LAST:event_lb_adminMouseEntered

    private void lb_adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_adminMouseExited
        // TODO add your handling code here:
        panel_admin.setBackground(Color.white);
        lb_admin.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb_adminMouseExited

    private void lb_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseClicked
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_lb_exitMouseClicked

    private void lb_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseEntered
        // TODO add your handling code here:
        panel_exit.setBackground(Color.red);
        lb_exit.setForeground(Color.white);
    }//GEN-LAST:event_lb_exitMouseEntered

    private void lb_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exitMouseExited
        // TODO add your handling code here:
        panel_exit.setBackground(Color.white);
        lb_exit.setForeground(Color.black);
    }//GEN-LAST:event_lb_exitMouseExited

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        // TODO add your handling code here:
        if (txt_usuario.getText().equals("Ingrese su nombre de usuario")) {
            txt_usuario.setText("");
            txt_usuario.setForeground(Color.black);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()) {
            txt_pass.setText("*****");
            txt_pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void txt_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMousePressed
        // TODO add your handling code here:
         if (String.valueOf(txt_pass.getPassword()).equals("*****")) {
            txt_pass.setText("");
            txt_pass.setForeground(Color.black);
        }
        if (txt_usuario.getText().isEmpty()) {
            txt_usuario.setText("Ingrese su nombre de usuario");
            txt_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_passMousePressed

    private void lb_entrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_entrarMouseEntered
        // TODO add your handling code here:
        panel_entrar.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_lb_entrarMouseEntered

    private void lb_entrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_entrarMouseExited
        // TODO add your handling code here:
        panel_entrar.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_lb_entrarMouseExited

    private void lb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_entrarMouseClicked
        // TODO add your handling code here:
        String usuario = txt_usuario.getText();
        String contraseñausuario = new String(txt_pass.getPassword());
        
        //inicio de la auntenticacion del boton
        if (usuario.equals("user") && contraseñausuario.equals("user")) {
            // Credenciales válidas
            JOptionPane.showMessageDialog(this, "Bienvenido al sistema de estacionamiento! ");
            MenuUsr m=new MenuUsr();
            m.setVisible(true);
            dispose();
            
            class_auto rango=new class_auto("Usuario");
            rango.setRangoLog("Usuario");
            
         
         

        } else {
            
            counter ++;
                    if (counter == 3) {
                JOptionPane.showMessageDialog(this, "Excediste el número de intentos. Espera 10 segundos.");
                //message.setText("Excediste el número de intentos. Espera 10 segundos.");
                lb_entrar.setEnabled(false);
                message.setText("Bloqueado");

                // Esperar 10 segundos antes de habilitar el botón de nuevo
                new Thread(() -> {
                    try {
                        TimeUnit.SECONDS.sleep(10);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                    counter = 0;
                    message.setText("Desbloqueado");
                    lb_entrar.setEnabled(true);
                    }).start();
                }
                    else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos. Intento " + counter + " de 3." );
                //message.setText("Usuario o contraseña incorrectos. Intento " + counter + " de 3.");
                   }
            }
    }//GEN-LAST:event_lb_entrarMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_usr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_usr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_admin;
    private javax.swing.JLabel lb_entrar;
    private javax.swing.JLabel lb_exit;
    private javax.swing.JLabel lb_root;
    private javax.swing.JLabel message;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_entrar;
    private javax.swing.JPanel panel_exit;
    private javax.swing.JPanel panel_root;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
